return {
    All = {
        "LIGHTNINGABUSE",
        "SUB2GAMERROBOT_EXP1",

        "Sub2Fer999",
        "Enyu_is_Pro",
        "JCWK",
        "StarcodeHEO",
        "MagicBUS",
        "KittGaming",
        "Sub2CaptainMaui",
        "Sub2OfficialNoobie",
        "TheGreatAce",
        "Sub2NoobMaster123",
        "Sub2Daigrock",
        "Axiore",
        "StrawHatMaine",
        "TantaiGaming",
        "Bluxxy",

        "KITT_RESET",
        "Sub2UncleKizaru",
        "SUB2GAMERROBOT_RESET1",

        "BIGNEWS",

        "fudd10_V2",
        "fudd10",
        "Fudd10",
        "CHANDLER",

        "BANEXPLOIT"
    }
}
