return {
  MeleeLists = {"Black Leg", "Electro", "Fishman Karate", "Dragon Claw", "Superhuman", "Death Step", "Sharkman Karate", "Electric Claw", "Dragon Talon", "Godhuman", "Sanguine Art"},
  MeleeRemotes = {
        ["Black Leg"] = {"BuyBlackLeg"},
        ["Electro"] = {"BuyElectro"},
        ["Fishman Karate"] = {"BuyFishmanKarate"},
        ["Dragon Claw"] = {
            {"BlackbeardReward", "DragonClaw", "1"},
            {"BlackbeardReward", "DragonClaw", "2"}
        },
        ["Superhuman"] = {"BuySuperhuman"},
        ["Death Step"] = {"BuyDeathStep"},
        ["Electric Claw"] = {"BuyElectricClaw"},
        ["Sharkman Karate"] = {"BuySharkmanKarate"},
        ["Dragon Talon"] = {"BuyDragonTalon"},
        ["Godhuman"] = {"BuyGodhuman"},
        ["Sanguine Art"] = {
            {"BuySanguineArt", true},
            {"BuySanguineArt"}
        }
    },
}
